### ISSUE TITLE
start_socket not found

### ISSUE THREAD

**Issue by vivek1729** [CptLemming/django-socket-server#1]
I did `pip install django-socket-server` and added `sockets.py` file modifying it according to my django application. I then run the following command as mentioned in the docs - `python manage.py start_socket`. I get the error saying - `Unknown command: 'start_socket'`.

Basically, I have an application called "foo" in the `INSTALLED_APPS` object. I added a `sockets.py` in that folder and it looks like this:

```
 from foo.namespace import EventNamespace
 class Namespace(EventNamespace):
 name = 'pingpong'
 def client_connected(self, client):
    super(Namespace, self).client_connected(client)

    print 'Send ping'
    self.emit_to(client, 'ping')

  def register_callbacks(self):
    return {
        'pong': self.pong
    }

 def pong(self, client, **kwargs):
     print 'Received pong event'
```

Would appreciate if you can guide me on how to use the django socket server in my existing django application. I realise that I am not referencing this module anywhere which is why I get the error. How do I set up the socket-server module in an existing django application?

**Comment by CptLemming** [comment]
Have you added `socket_server` to your installed apps list?

```
INSTALLED_APPS = (
    ...
    'socket_server',
    ...
)
```

**Comment by vivek1729** [comment]
Yes, I just did. And when I do, and change the `sockets.py` file to have `from socket_server.namespace` instead of `foo.namespace`. I get the following error when I try to do `python manage.py runserver`

```
System check identified no issues (0 silenced).
Unhandled exception in thread started by <function wrapper at 0x10a5aa488>
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check_migrations()
  File "/Library/Python/2.7/site-packages/django/core/management/commands/runserver.py", line 168, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/Library/Python/2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Library/Python/2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/Library/Python/2.7/site-packages/django/db/migrations/loader.py", line 182, in build_graph
    self.load_disk()
  File "/Library/Python/2.7/site-packages/django/db/migrations/loader.py", line 123, in load_disk
    "creating Django migrations." % app_config.label
django.db.migrations.loader.BadMigrationError: Migrated app 'socket_server' contains South migrations. Make sure all numbered South migrations are deleted prior to creating Django migrations.
```

**Comment by vivek1729** [comment]
So I had an existing web server with django where I served a static html file. That file would basically serve as the socket client through javascript. The idea is to have a socket server in django. So I just installed your module and created a `sockets.py` in my existing application folder referencing the earlier application name i.e. "foo". Then as you mentioned, I added "socket_server" to the installed apps and added a `sockets.py` outside the application folder i.e. along side the `manage.py` file. As soon as I add the `socket_server` app to my Installed apps, I get the error mentioned above.

**Comment by CptLemming** [comment]
Ah I see now. This app only works with Django below 1.7. I haven't updated this in a long time as I started using another library: [swampdragon](https://github.com/jonashagstedt/swampdragon).

It has more features than what this simple app offers and is much better supported. If you're looking into adding websockets to your Django application I can't recommend this app enough!
